### ISSUE TITLE
there is an error when run the generated lua file with luajit

### ISSUE THREAD

**Issue by ming871** [lordoffox/adata#2]
ADL FILE:testadata.adl
namespace=test;
RoomMovePoint{
    int64 lastMoveTime;
    float32 x;
    float32 y;
    float32 z;
    float32 chassisAngle;
    float32 turretAngle;
    float32 gunAngle;
}

LUA FILE:testadata.lua
local adata = require("adata_core")
local testadata_adl = require("testproto_adl")

local buf_len = 60
local stream = adata.new_buf(buf_len)
local p = testadata_adl.roommovepoint()
p.lastmovetime = 1427557006234
p.x = 1000.1
p.y = 1000.1
p.z = 1000.1
p.chassisangle = 1000.1
p.turretangle = 1000.1
p.gunangle = 1000.1
local ec = p:write(stream)

EXECUTE WITH LUAJIT CMD:
luajit: ./testproto_adl.lua:96: attempt to call upvalue 'szof_i64' (a nil value)
stack traceback:
    ./testproto_adl.lua:96: in function 'size_of'
    ./testproto_adl.lua:179: in function 'write'
    testadataluajit.lua:18: in function 'test'
    testadataluajit.lua:22: in main chunk
    [C]: at 0x00404270

**Comment by nousxiong** [comment]
You must have namespace:

namespace = xxx;

item { int64 id; int32 type; int32 level; }

**Comment by ming871** [comment]
thank you very much!
