### ISSUE TITLE
there is an error when run the generated lua file with luajit

### ISSUE THREAD

**Issue by ming871** [lordoffox/adata#3]
ADL FILE:testproto.adl
namespace=test;
RoomMovePoint{
int64 lastMoveTime;
float32 x;
float32 y;
float32 z;
float32 chassisAngle;
float32 turretAngle;
float32 gunAngle;
}

LUA FILE:testadata.lua
local adata = require("adata_core")
local testadata_adl = require("testproto_adl")

local buf_len = 60
local stream = adata.new_buf(buf_len)
local p = testadata_adl.roommovepoint()
p.lastmovetime = 1427557006234
p.x = 1000.1
p.y = 1000.1
p.z = 1000.1
p.chassisangle = 1000.1
p.turretangle = 1000.1
p.gunangle = 1000.1
local ec = p:write(stream)

EXECUTE WITH LUAJIT CMD:
luajit: ./testproto_adl.lua:96: attempt to call upvalue 'szof_i64' (a nil value)
stack traceback:
./testproto_adl.lua:96: in function 'size_of'
./testproto_adl.lua:179: in function 'write'
testadataluajit.lua:18: in function 'test'
testadataluajit.lua:22: in main chunk
[C]: at 0x00404270

**Comment by ming871** [comment]
no problem when embed in cpp

**Comment by nousxiong** [comment]
Did you called adata::lua::init_adata_corec(L); in your cpp code?

**Comment by ming871** [comment]
it ok after added "adata::lua::init_adata_corec(L);" in the code! thanks

**Comment by ming871** [comment]
adata is good job, I will use it in my game.

**Comment by nousxiong** [comment]
Under adata/example/lua, there is a lua example, you can refer to it.

**Comment by nousxiong** [comment]
Thx, :-D

**Comment by ming871** [comment]
I create another issue:https://github.com/lordoffox/adata/issues/4
