### ISSUE TITLE
Can adata add service support like google protobuf?

### ISSUE THREAD

**Issue by ming871** [lordoffox/adata#4]
This is useful when create a RPC system.

**Comment by nousxiong** [comment]
你能看懂中文吗

**Comment by ming871** [comment]
来吧

**Comment by nousxiong** [comment]
稍等，我找另一个作者，他在忙点事

**Comment by ming871** [comment]
好的

**Comment by lordoffox** [comment]
来了，adata不会直接支持rpc，需要自己包装下，rpc的方式太重了，adata是一个很轻量的库，如果非常有需要会以另外的库的方式提供。

**Comment by ming871** [comment]
确实没有必要做完整的RPC，这样adata更通用一些，实现的话也只需要生成存根就可以了。

**Comment by ming871** [comment]
只是个建议 ：-D

**Comment by lordoffox** [comment]
非常感谢使用adata，也非常欢迎建议
另外qq群120274115，欢迎来交流adata，gce方面的问题
